---
title: "The Power of Efficiency"
format: html
editor: visual
---

As we’ve said in the class efficiency is a pivotal component of statistical computing (and data science). In this essay, give an explanation of what that term “efficiency” means in relation to statistical computing and describe some places where you encountered efficiency and understood its importance. Your essay should address the following questions:

-   What is the definition of “efficiency”?

-   What does efficiency look like in statistical computing / data science?

-   What does efficiency allow you to do?

-   Why is efficiency important?

-   Where did you encounter efficiency, and what were some [“a-ha” moments](https://www.merriam-webster.com/dictionary/aha%20moment) you had about efficiency? (For the latter, tie each a-ha moment to an artifact in the portfolio.)

**Efficiency** **to me means that you are able to accurately create code to solve a given problem while doing it in a way that is not repetitive and utilizes only what is necessary to limit chances for errors. In statistical computing and data science, efficient code can look like calling a function only once or iterating a function across multiple variables. Efficiency allows you to focus on writing a good program that you can access with a function call and by doing it this way you save time and are less error prone. When I finally understood how to implement summarize(across()) and write functions, I understood how useful it is to type efficient code. DVS-4 shows my ability to use summarize and across while in PE-2 and PE-3 I explore functions and the use of map functions which also allowed me to become a more efficient coder.**
