---
title: "Lightening Round Essays"
format: html
editor: visual
---

**Answer each of the following questions with *one sentence* including a brief explanation.**

1.  Finish the sentence with another student’s name: "If \[Name of Student\] doesn’t earn an A, then nobody should, because..." Explain your choice and your reasoning.

    **If Miriam R doesn't earn an A, then nobody should because she was really good about asking questions, making thorough revisions, worked well as a partner, and really engaged with the material in a thoughtful way.**

2.  What was the most difficult part of the class for you? List a general topic, a specific problem, a kind of work we did, etc. and explain why.

    **The most difficult part of this class was the labs because they required a lot of thinking and problem solving, but it could be hard to get started on problems if there wasn't enough guidance.**

3.  What was the easiest part of the class for you? Explain why.

    **The easiest part of the class for me was the ability to work with my peers because I am used to working on teams and the PA roles were helpful for breaking up the work in an even way.**

4.  What part of the class surprised or interested you the most? Explain why.

    **The part of this class that interested me the most was the application of the material to my research where I have switched over to using R for all of my statistics even early on in the quarter.**

5.  Give one piece of advice to a student just beginning a quarter of STAT 331 that will help them be successful in learning.

    **I would recommend to them that it is important to ask questions and try to stay on top of the work because it is hard to do the labs in only a few hours.**
